### ISSUE TITLE
Not able to Install using npm install

### ISSUE THREAD

**Issue by Jayendran-p** [elvisfernandes/ng2-dfservice#1]
Getting the following error when i try npm install:

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng2-dfservice"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-dfservice@0.0.3 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-dfservice@0.0.3 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the ng2-dfservice package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-dfservice
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ng2-dfservice
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jay/npm-debug.log

**Comment by elvisfernandes** [comment]
Hi @Jayendran-p,

I seems like you don't have typings installed. Try `npm install typings` and then `npm install ng2-dfservice` again.

Let me know if this fix the issue with your installation.

**Comment by Jayendran-p** [comment]
Thanks @elvisfernandes It fixed the issue. Your code is super useful as we are migrating from angular 1.0 to 2.0 using DF. Also can you provide sample code for how to implement login and logout.

**Comment by elvisfernandes** [comment]
Hi @Jayendran-p 

To login / logout you just need to call the login / logout methods from your DFService instance, like this:

```
// DFService will handle session_token storage
// It will also return an Observable so you can be notified when
// login() is finished - but not necessary, depending on your implementation
this.dfservice.login('your@email.com', 'your_password');
this.dfservice.logout();
```

In the [dfservice-example repo](https://github.com/elvisfernandes/dfservice-example) I [added an example](https://github.com/elvisfernandes/dfservice-example/commit/87c84e738d7b22a71d3ad21a577e630fb36c5fda) on how to use login/logout functions. Hope this helps.

**Comment by elvisfernandes** [comment]
Once this is not really a issue with this repo, I'm closing this ticket.
